version: '2'
services:
  hockeypuck:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "11370:11370"
    - "11371:11371"
    restart: always
    depends_on:
    - postgres
    volumes:
    - ./etc:/hockeypuck/etc
    - ./keydump:/hockeypuck/import/dump
    - hkp_data:/hockeypuck/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=hkp
    volumes:
    - pg_data:/var/lib/postgresql/data

volumes:
  hkp_data: {}
  pg_data: {}
