name: hockeypuck
version: git
summary: OpenPGP Public Keyserver
description: |
  Hockeypuck is an OpenPGP Key Server that implements the HTTP
  Keyserver Protocol and the SKS database reconciliation protocol.

architectures:
- build-on: amd64
  run-on: amd64

base: core18
confinement: strict
grade: stable

apps:
  hockeypuck:
    command: bin/hockeypuck-wrapper
    daemon: simple
    plugs:
      - network
      - network-bind
  config:
    command: hockeypuck-config-wrapper
  dump:
    command: bin/hockeypuck-dump-wrapper
    plugs:
      - home
      - network
  load:
    command: bin/hockeypuck-load-wrapper
    plugs:
      - home
      - network
  pbuild:
    command: bin/hockeypuck-pbuild-wrapper
    plugs:
      - network

parts:
  hockeypuck:
    build-environment:
      # https://github.com/golang/go/issues/33840
      - CGO_ENABLED: "0"
    build-snaps:
      - go/1.15/stable
    plugin: make
    make-parameters:
      - prefix=
      - statedir=
    source: .

  wrappers:
    plugin: dump
    source: src/hockeypuck/server/snap
    organize:
      "*-wrapper": bin/
    stage:
      - bin/*
    prime:
      - bin/*
