.TH hockeypuck-mgo 1 "07 Sep 2012" hockeypuck "hockeypuck"
.SH NAME
\fBhockeypuck-load\fP \- OpenPGP Key Server Loader

.SH SYNOPSIS
\fBhockeypuck-load\fP [-hkp=<IP>:PORT] [-path=PATH]

.SH DESCRIPTION

\fBhockeypuck-load\fP reads OpenPGP public keys from a keyring file and loads them into an OpenPGP Keyserver using the HKP protocol.

Options and modes for running hockeypuck are described below:

.SH OPTIONS
.TP
\fB-hkp=HOST:PORT\fP
Add keys to the HKP server listening on HOST:PORT. If not specified, keys will be added to localhost:11371.

.TP
\fB-path=PATH\fP
Path to an OpenPGP public keyring file. The file must be binary, not armored format. These files typically have a .pgp or .gpg file extension. Glob wildcard patterns are also supported.

To load from standard input, use -path=/dev/stdin.

.SH CAVEATS
hockeypuck-load can place heavy load on some keyserver implementations. Use with caution, and always with permission.

.SH BUGS
Bugs, known issues and features in development are tracked at \fBhttps://bugs.launchpad.net/hockeypuck\fP.

.SH SEE ALSO
.PD 0
.TP
The OpenPGP HTTP Keyserver Protocol (HKP)
http://ietfreport.isoc.org/all-ids/draft-shaw-openpgp-hkp-00.txt
.TP
\fBhockeypuck-mgo\fP(1), \fBhockeypuck-pq\fP(1), \fBgpg\fP(1), \fBmongo\fP(1), \fIhttps://launchpad.net/hockeypuck\fP
.PD

.SH AUTHOR
Casey Marshall <casey.marshall@gmail.com>

