.TH hockeypuck 1 "07 Sep 2012" hockeypuck "hockeypuck"
.SH NAME
\fBhockeypuck\fP \- OpenPGP Key Server

.SH SYNOPSIS

\fBhockeypuck\fP COMMAND COMMAND_OPTIONS

.SH DESCRIPTION

\fBhockeypuck\fP is an public keyserver that implements HKP
(HTTP Keyserver Protocol) for serving OpenPGP public keys. Other
PKIs may be supported in upcoming releases.

.SH COMMANDS
Options and modes for the supported hockeypuck commands are described below.

.SH hockeypuck run
Run the Hockeypuck HKP and public key synchronization services.
.TP
\fB--config\fP (= "")
    Hockeypuck configuration file
.TP
\fB--cpuprof\fP (= false)
    Enable CPU profiling

.SH hockeypuck load
Load public key material from files in RFC 4880 binary keyring
format into the Hockeypuck database.
.TP
\fB--config\fP (= "")
    Hockeypuck configuration file
.TP
\fB--cpuprof\fP  (= false)
    Enable CPU profiling
.TP
\fB--ignore-dups\fP  (= false)
    Ignore duplicate entries
.TP
\fB--path\fP (= "")
    OpenPGP keyring file path or glob pattern
.TP
\fB--txn-size\fP  (= 5000)
    Transaction size; public keys per commit

.SH hockeypuck db
Manage Hockeypuck relational database and prefix tree file.
.TP
\fB--config\fP (= "")
    Hockeypuck configuration file
.TP
\fB--cpuprof\fP  (= false)
    Enable CPU profiling
.TP
\fB--create-constraints\fP  (= false)
    Create primary key, unique and foreign key constraints
.TP
\fB--create-tables\fP  (= true)
    Create tables if they don't exist
.TP
\fB--dedup\fP  (= false)
    De-duplicate primary key and unique constraint columns
.TP
\fB--drop-constraints\fP  (= false)
    Drop all primary key, unique and foreign key constraints

.SH hockeypuck pbuild
Rebuild the prefix tree data file from the public keys contained
in the relational database.
.TP
\fB--cache\fP  (= 64)
    Max diskv cache size (MB)
.TP
\fB--config\fP (= "")
    Hockeypuck configuration file
.TP
\fB--cpuprof\fP  (= false)
    Enable CPU profiling
.TP
\fB--ignore-dups\fP  (= false)
    Ignore duplicate entries
.TP
\fB--nworkers\fP  (= GOMAXPROCS)
    Number of concurrent ptree writers

.SH BUGS
Bugs, known issues and features in development are tracked at \fBhttps://github.com/hockeypuck/hockeypuck\fP.

.SH SEE ALSO
.PD 0
.TP
RFC 4880, RFC 6637, the OpenPGP HTTP Keyserver Protocol (HKP) draft specification
(http://ietfreport.isoc.org/all-ids/draft-shaw-openpgp-hkp-00.txt).
.TP
\fBgpg\fP(1), \fIhttp://hockeypuck.github.io\fP, \fIhttps://github.com/hockeypuck/hockeypuck\fP
.PD

.SH AUTHOR
Casey Marshall <cmars@cmarstech.com>
