---
- name: Stop SKS
  service: name=sks state=stopped
- name: Ensure DB utils available
  apt: update_cache=yes pkg=db-util state=present
- name: Development rebuild of sks-dump-ptree
  local_action: shell go build -o files/sks-dump-ptree github.com/cmars/conflux/cmd/sks-dump-ptree
- name: Install sks-dump-ptree
  copy: src=files/sks-dump-ptree dest=/usr/bin/sks-dump-ptree mode=0755
- name: Dump the ptree
  shell: db_dump /var/lib/sks/PTree/ptree | /usr/bin/sks-dump-ptree > /tmp/sks-recon-ptree.txt
- name: Fetch the dump
  fetch: src=/tmp/sks-recon-ptree.txt dest=dumps/sks-recon-ptree.txt flat=yes
- name: Start SKS
  service: name=sks state=started
