#!/bin/bash -ex

# Get our current and last built revision
REVNO=$(bzr log | grep -m1 "^revno: " | awk '{print $2}')

if [ -z "$1" ]; then
	DISTS=$(distro-info --supported | egrep -v 'hardy|lucid|oneiric')
else
	DISTS=$1
fi

bzr revert debian/changelog

# Detect whether this is a development build or production release
DEVBUILD=$(head -1 debian/changelog | grep \~ && echo true)

# Build for each supported Ubuntu version
for d in $DISTS; do
	# Revert any changes (ie, debian/changelog)
	bzr revert debian/changelog
	bzr revert debian/control

	# Remove nikola from Build-Depends on distros lacking backports
	if [[ "$d" =~ ^(precise|quantal)$ ]]; then
		sed -i 's/, nikola.*//' debian/control
	fi

	if [ -n "$DEVBUILD" ]; then
		# Append bzr revision and release distro info
		sed -i -e "s/) [a-zA-Z0-9].*;/~bzr$REVNO~$d) $d;/i" debian/changelog
	else
		# Append release distro info
		sed -i -e "s/) [a-zA-Z0-9].*;/.0${REVNO}~$d) $d;/i" debian/changelog
	fi
	# Build source package
	make debsrc
	# Update changelog timestamp and committer
	dch -r ""
done

bzr revert debian/changelog
