#!/bin/bash -ex

function revert_debfiles(){
	git checkout ./debian
}

# Get our current and last built revision
REVNO=$(date '+%Y%m%d')+$(git rev-parse --short HEAD)

if [ -z "$1" ]; then
	DISTS=$(distro-info --supported | egrep -v 'hardy|lucid|oneiric')
else
	DISTS=$1
fi

revert_debfiles

# Detect whether this is a development build or production release
DEVBUILD=$(head -1 debian/changelog | grep \~ && echo true)

# Build for each supported Ubuntu version
for d in $DISTS; do
	# Revert any changes (ie, debian/changelog)
	revert_debfiles

	# Remove nikola from Build-Depends on distros lacking backports
	if [[ "$d" =~ ^(precise|quantal)$ ]]; then
		sed -i 's/, nikola.*//' debian/control
	fi

	if [ -n "$DEVBUILD" ]; then
		# Append bzr revision and release distro info
		sed -i -e "s/) \([a-zA-Z0-9].*\);/$1~dev$REVNO~$d) $d;/i" debian/changelog
	else
		# Append release distro info
		sed -i -e "s/) \([a-zA-Z0-9].*\);/$1~r$REVNO~$d) $d;/i" debian/changelog
	fi
	# Build source package
	make debsrc
	# Update changelog timestamp and committer
	dch -r ""
done

revert_debfiles
