#!/bin/bash -e

service hockeypuck stop || true

# Construct a new membership file
PARTNERS=""
for member in $(relation-list); do
	if [ -n "$PARTNERS" ]; then
		SEP=","
	else
		SEP=""
	fi
	PARTNERS="$(relation-get private-address $member):11370"$SEP"$PARTNERS"
done

cat >/etc/hockeypuck/hockeypuck.conf.d/03-recon <<EOF

[conflux.recon]
reconPort=11370
httpPort=11371
partners=["$PARTNERS"]
filters=["yminsky.dedup"]

EOF

cat /etc/hockeypuck/hockeypuck.conf.d/* > /etc/hockeypuck/hockeypuck.conf

service hockeypuck start
