version: '3.7'
services:
  haproxy:
    image: haproxy:2.6-alpine
    ports:
    - "${HAP_HTTP_HOST_PORT:-80}:80"
    - "${HAP_HTTPS_HOST_PORT:-443}:443"
    - "${HAP_HKP_HOST_PORT:-11371}:11371"
    - "${HAP_PEER_HOST_PORT:-127.0.0.1:1395}:1395"
    - "${HAP_ADMIN_HOST_PORT:-127.0.0.1:1396}:1396"
    user: root
    restart: always
    init: true
    hostname: haproxy
    environment:
    - ALIAS_FQDNS
    - CLUSTER_FQDNS
    - FQDN
    - KEYSERVER_HOST_PORT
    - HAP_DHPARAM_FILE=/etc/letsencrypt/ssl-dhparams.pem
    - HAP_CONF_DIR=/usr/local/etc/haproxy
    - HAP_CACHE_DIR=/var/cache/haproxy
    - HAP_LOG_FORMAT
    - HAP_BEHIND_CLOUDFLARE
    - HAP_BEHIND_PROXY
    - HAP_BEHIND_PROXY_EXCEPT_HKP
    - HAP_DISABLE_PROMETHEUS=true
    - HAP_DISABLE_CERTBOT=true
    - HAP_DISABLE_SSL=true
    depends_on:
    - haproxy_cache
    - haproxy_internal
    volumes:
    - ./haproxy-entrypoint.sh:/usr/local/bin/haproxy-entrypoint.sh
    - ./haproxy/etc:/usr/local/etc/haproxy
    - haproxy_cache:/var/cache/haproxy
    entrypoint: "/usr/local/bin/haproxy-entrypoint.sh -f /usr/local/etc/haproxy/haproxy.d"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  haproxy_internal:
    image: haproxy:2.6-alpine
    user: root
    restart: always
    ports:
      - "${HAP_INTERNAL_ADMIN_HOST_PORT:-127.0.0.1:1397}:1396"
    environment:
    - RELOAD_INTERVAL=0
    hostname: haproxy-internal
    volumes:
    - ./haproxy/etc/haproxy-internal.cfg:/usr/local/etc/haproxy/haproxy.cfg
    entrypoint: "/bin/sh -c 'export HOSTNAME=$$(hostname); export HOST_IP=$$(hostname -i); haproxy -f /usr/local/etc/haproxy/haproxy.cfg'"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  haproxy_cache:
    image: instrumentisto/rsync-ssh
    restart: always
    volumes:
    - haproxy_cache:/var/cache/haproxy
    entrypoint: "/bin/sh -c 'trap exit TERM; touch /var/cache/haproxy/tor_exit_relays.list; while :; do sleep 1800; wget \"${TOR_EXIT_RELAYS_URL}\" -O /var/cache/haproxy/tor_exit_relays.list; done'"
    logging:
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  haproxy_cache: {}
